name: PHP tests
on: [push, pull_request]
jobs:
  # Check there is no syntax errors in the project
  php-linter:
    name: PHP Syntax check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: PHP syntax checker 7.1
        uses: prestashop/github-action-php-lint/7.1@master

      - name: PHP syntax checker 7.2
        uses: prestashop/github-action-php-lint/7.2@master

      - name: PHP syntax checker 7.3
        uses: prestashop/github-action-php-lint/7.3@master

      - name: PHP syntax checker 7.4
        uses: prestashop/github-action-php-lint/7.4@master

      - name: PHP syntax checker 8.0
        uses: prestashop/github-action-php-lint/8.0@master

      - name: PHP syntax checker 8.1
        uses: prestashop/github-action-php-lint/8.1@master

      - name: PHP syntax checker 8.2
        uses: prestashop/github-action-php-lint/8.2@master

      - name: PHP syntax checker 8.3
        uses: prestashop/github-action-php-lint/8.3@master

      - name: PHP syntax checker 8.4
        uses: prestashop/github-action-php-lint/8.4@master

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: PrestaShop/.github/.github/actions/php-ci/php-cs@master
        with:
          php-version: '8.1'

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - presta-version: '1.7.7.8'
            php-version: '7.1'
            php-stan-version: '^0.12'
          - presta-version: '1.7.8.11'
            php-version: '7.4'
            php-stan-version: '^2.1'
          - presta-version: '8.0.5'
            php-version: '7.4'
            php-stan-version: '^2.1'
          - presta-version: '9.0.3'
            php-version: '8.1'
            php-stan-version: '^2.1'
          - presta-version: 'develop'
            php-version: '8.1'
            php-stan-version: '^2.1'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          path: ${{ github.event.repository.name }}
      
      - uses: PrestaShop/.github/.github/actions/php-ci/phpstan@master
        with:
          php-version: ${{ matrix.php-version }}
          presta-version: ${{ matrix.presta-version }}
          module-name: ${{ github.event.repository.name }}
          phpstan-level: '5'
          phpstan-config: 'tests/php/phpstan/phpstan-${{ matrix.presta-version }}.neon'
          phpstan-version: ${{ matrix.php-stan-version }}
          composer-version: '2.2.18'
